=== 3dcitydb/importer-exporter/impexp-core/src/main/resources/org/citydb/database/schema/3dcitydb-schema.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema elementFormDefault="qualified" version="1.0" targetNamespace="http://www.3dcitydb.org/database/schema/3.0" xmlns="http://www.3dcitydb.org/database/schema/3.0" xmlns:tns="http://www.3dcitydb.org/database/schema/3.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="schemaMapping" type="schemaMapping"/>

  <xs:complexType name="schemaMapping">
    <xs:sequence>
      <xs:element name="metadata" type="metadata" minOccurs="0"/>
      <xs:element name="applicationSchemas">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="schema" type="schema" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="attributeTypes" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="attributeType" type="complexAttributeType" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="complexTypes" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="complexType" type="complexType" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="objectTypes" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="objectType" type="objectType" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="featureTypes" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="featureType" type="featureType" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="propertyInjections" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="propertyInjection" type="propertyInjection" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="metadata">
    <xs:sequence>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="version" type="xs:string" minOccurs="0"/>
      <xs:element name="description" type="xs:string" minOccurs="0"/>
      <xs:element name="dbPrefix" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="schema">
    <xs:sequence>
      <xs:element name="namespace" type="namespace" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:ID" use="required"/>
    <xs:attribute name="xmlPrefix" type="xs:string"/>
    <xs:attribute name="isADERoot" type="xs:boolean"/>
  </xs:complexType>

  <xs:complexType name="namespace">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="context" type="cityGMLContext" use="required"/>
        <xs:attribute name="schemaLocation" type="xs:string"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="complexAttributeType">
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="attribute" type="attribute"/>
        <xs:element name="complexAttribute" type="complexAttribute"/>
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="id" type="xs:ID" use="required"/>
    <xs:attribute name="table" type="xs:string"/>
  </xs:complexType>

  <xs:complexType name="attribute">
    <xs:complexContent>
      <xs:extension base="abstractAttribute">
        <xs:sequence>
          <xs:choice minOccurs="0">
            <xs:element name="join" type="join"/>
            <xs:element name="reverseJoin" type="reverseJoin"/>
          </xs:choice>
        </xs:sequence>
        <xs:attribute name="column" type="xs:string" use="required"/>
        <xs:attribute name="type" type="simpleType" use="required"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="abstractAttribute" abstract="true">
    <xs:complexContent>
      <xs:extension base="abstractProperty">
        <xs:sequence/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="abstractProperty" abstract="true">
    <xs:complexContent>
      <xs:extension base="abstractPathElement">
        <xs:sequence/>
        <xs:attribute name="minOccurs" type="xs:int"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="abstractPathElement" abstract="true">
    <xs:sequence/>
    <xs:attribute name="path" type="xs:string" use="required"/>
    <xs:attribute name="schema" type="xs:string" use="required"/>
    <xs:attribute name="queryable" type="xs:boolean"/>
  </xs:complexType>

  <xs:complexType name="join">
    <xs:complexContent>
      <xs:extension base="abstractJoin">
        <xs:sequence>
          <xs:element name="condition" type="condition" minOccurs="0" maxOccurs="unbounded"/>
          <xs:element name="treeHierarchy" type="treeHierarchy" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="table" type="xs:string" use="required"/>
        <xs:attribute name="fromColumn" type="xs:string" use="required"/>
        <xs:attribute name="toColumn" type="xs:string" use="required"/>
        <xs:attribute name="toRole" type="tableRole" use="required"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="abstractJoin" abstract="true">
    <xs:sequence/>
  </xs:complexType>

  <xs:complexType name="condition">
    <xs:sequence/>
    <xs:attribute name="column" type="xs:string" use="required"/>
    <xs:attribute name="value" type="xs:string" use="required"/>
    <xs:attribute name="type" type="simpleType" use="required"/>
  </xs:complexType>

  <xs:complexType name="treeHierarchy">
    <xs:sequence/>
    <xs:attribute name="rootColumn" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="reverseJoin">
    <xs:complexContent>
      <xs:extension base="abstractJoin">
        <xs:sequence/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="complexAttribute">
    <xs:complexContent>
      <xs:extension base="abstractAttribute">
        <xs:sequence>
          <xs:choice minOccurs="0">
            <xs:element name="join" type="join"/>
            <xs:element name="reverseJoin" type="reverseJoin"/>
          </xs:choice>
          <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="attribute" type="attribute"/>
            <xs:element name="complexAttribute" type="complexAttribute"/>
          </xs:choice>
        </xs:sequence>
        <xs:attribute name="type" type="xs:string"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="complexType">
    <xs:complexContent>
      <xs:extension base="abstractPathElement">
        <xs:sequence>
          <xs:element name="extension" type="complexTypeExtension" minOccurs="0"/>
          <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="attribute" type="attribute"/>
            <xs:element name="complexAttribute" type="complexAttribute"/>
            <xs:element name="complexProperty" type="complexProperty"/>
            <xs:element name="objectProperty" type="objectProperty"/>
            <xs:element name="featureProperty" type="featureProperty"/>
            <xs:element name="geometryProperty" type="geometryProperty"/>
            <xs:element name="implicitGeometryProperty" type="implicitGeometryProperty"/>
          </xs:choice>
        </xs:sequence>
        <xs:attribute name="abstract" type="xs:boolean"/>
        <xs:attribute name="id" type="xs:ID"/>
        <xs:attribute name="table" type="xs:string"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="complexTypeExtension">
    <xs:sequence>
      <xs:element name="join" type="join" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="base" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="complexProperty">
    <xs:complexContent>
      <xs:extension base="abstractRefOrInlineTypeProperty">
        <xs:sequence>
          <xs:element name="type" type="complexType" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="refType" type="xs:string"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="abstractRefOrInlineTypeProperty" abstract="true">
    <xs:complexContent>
      <xs:extension base="abstractTypeProperty">
        <xs:sequence/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="abstractTypeProperty" abstract="true">
    <xs:complexContent>
      <xs:extension base="abstractProperty">
        <xs:sequence>
          <xs:choice minOccurs="0">
            <xs:element name="join" type="join"/>
            <xs:element name="joinTable" type="joinTable"/>
          </xs:choice>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="joinTable">
    <xs:complexContent>
      <xs:extension base="abstractJoin">
        <xs:sequence>
          <xs:element name="join" type="join"/>
          <xs:element name="inverseJoin" type="join"/>
        </xs:sequence>
        <xs:attribute name="table" type="xs:string" use="required"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="objectProperty">
    <xs:complexContent>
      <xs:extension base="abstractRefTypeProperty">
        <xs:sequence/>
        <xs:attribute name="target" type="xs:string" use="required"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="abstractRefTypeProperty" abstract="true">
    <xs:complexContent>
      <xs:extension base="abstractTypeProperty">
        <xs:sequence/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="featureProperty">
    <xs:complexContent>
      <xs:extension base="abstractRefTypeProperty">
        <xs:sequence/>
        <xs:attribute name="target" type="xs:string" use="required"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="geometryProperty">
    <xs:complexContent>
      <xs:extension base="abstractProperty">
        <xs:sequence>
          <xs:choice minOccurs="0">
            <xs:element name="join" type="join"/>
            <xs:element name="reverseJoin" type="reverseJoin"/>
          </xs:choice>
        </xs:sequence>
        <xs:attribute name="lod" type="xs:int"/>
        <xs:attribute name="refColumn" type="xs:string"/>
        <xs:attribute name="inlineColumn" type="xs:string"/>
        <xs:attribute name="type" type="geometryType" use="required"/>
        <xs:attribute name="srsDimension" type="xs:int"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="implicitGeometryProperty">
    <xs:complexContent>
      <xs:extension base="abstractRefTypeProperty">
        <xs:sequence/>
        <xs:attribute name="lod" type="xs:int" use="required"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="objectType">
    <xs:complexContent>
      <xs:extension base="abstractPathElement">
        <xs:sequence>
          <xs:element name="extension" type="objectTypeExtension" minOccurs="0"/>
          <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="attribute" type="attribute"/>
            <xs:element name="complexAttribute" type="complexAttribute"/>
            <xs:element name="complexProperty" type="complexProperty"/>
            <xs:element name="objectProperty" type="objectProperty"/>
            <xs:element name="featureProperty" type="featureProperty"/>
            <xs:element name="geometryProperty" type="geometryProperty"/>
            <xs:element name="implicitGeometryProperty" type="implicitGeometryProperty"/>
          </xs:choice>
        </xs:sequence>
        <xs:attribute name="abstract" type="xs:boolean"/>
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="table" type="xs:string" use="required"/>
        <xs:attribute name="objectClassId" type="xs:int" use="required"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="objectTypeExtension">
    <xs:sequence>
      <xs:element name="join" type="join" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="base" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="featureType">
    <xs:complexContent>
      <xs:extension base="abstractPathElement">
        <xs:sequence>
          <xs:element name="extension" type="featureTypeExtension" minOccurs="0"/>
          <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="attribute" type="attribute"/>
            <xs:element name="complexAttribute" type="complexAttribute"/>
            <xs:element name="complexProperty" type="complexProperty"/>
            <xs:element name="objectProperty" type="objectProperty"/>
            <xs:element name="featureProperty" type="featureProperty"/>
            <xs:element name="geometryProperty" type="geometryProperty"/>
            <xs:element name="implicitGeometryProperty" type="implicitGeometryProperty"/>
          </xs:choice>
          <xs:element name="adeHook" type="adeHook" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="abstract" type="xs:boolean"/>
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="table" type="xs:string" use="required"/>
        <xs:attribute name="objectClassId" type="xs:int" use="required"/>
        <xs:attribute name="topLevel" type="xs:boolean"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="featureTypeExtension">
    <xs:sequence>
      <xs:element name="join" type="join" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="base" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="adeHook">
    <xs:sequence/>
    <xs:attribute name="name" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="propertyInjection">
    <xs:sequence>
      <xs:element name="join" type="join" minOccurs="0"/>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="attribute" type="injectedSimpleAttribute"/>
        <xs:element name="complexAttribute" type="injectedComplexAttribute"/>
        <xs:element name="complexProperty" type="injectedComplexProperty"/>
        <xs:element name="objectProperty" type="injectedObjectProperty"/>
        <xs:element name="featureProperty" type="injectedFeatureProperty"/>
        <xs:element name="geometryProperty" type="injectedGeometryProperty"/>
        <xs:element name="implicitGeometryProperty" type="injectedImplicitGeometryProperty"/>
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="table" type="xs:string" use="required"/>
    <xs:attribute name="defaultBase" type="xs:string"/>
  </xs:complexType>

  <xs:complexType name="injectedSimpleAttribute">
    <xs:complexContent>
      <xs:extension base="attribute">
        <xs:sequence/>
        <xs:attribute name="base" type="xs:string"/>
        <xs:attribute name="context" type="cityGMLContext"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="injectedComplexAttribute">
    <xs:complexContent>
      <xs:extension base="complexAttribute">
        <xs:sequence/>
        <xs:attribute name="base" type="xs:string"/>
        <xs:attribute name="context" type="cityGMLContext"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="injectedComplexProperty">
    <xs:complexContent>
      <xs:extension base="complexProperty">
        <xs:sequence/>
        <xs:attribute name="base" type="xs:string"/>
        <xs:attribute name="context" type="cityGMLContext"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="injectedObjectProperty">
    <xs:complexContent>
      <xs:extension base="objectProperty">
        <xs:sequence/>
        <xs:attribute name="base" type="xs:string"/>
        <xs:attribute name="context" type="cityGMLContext"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="injectedFeatureProperty">
    <xs:complexContent>
      <xs:extension base="featureProperty">
        <xs:sequence/>
        <xs:attribute name="base" type="xs:string"/>
        <xs:attribute name="context" type="cityGMLContext"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="injectedGeometryProperty">
    <xs:complexContent>
      <xs:extension base="geometryProperty">
        <xs:sequence/>
        <xs:attribute name="base" type="xs:string"/>
        <xs:attribute name="context" type="cityGMLContext"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="injectedImplicitGeometryProperty">
    <xs:complexContent>
      <xs:extension base="implicitGeometryProperty">
        <xs:sequence/>
        <xs:attribute name="base" type="xs:string"/>
        <xs:attribute name="context" type="cityGMLContext"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:simpleType name="cityGMLContext">
    <xs:restriction base="xs:string">
      <xs:enumeration value="citygml-2.0"/>
      <xs:enumeration value="citygml-1.0"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="simpleType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="string"/>
      <xs:enumeration value="integer"/>
      <xs:enumeration value="double"/>
      <xs:enumeration value="boolean"/>
      <xs:enumeration value="date"/>
      <xs:enumeration value="timestamp"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="tableRole">
    <xs:restriction base="xs:string">
      <xs:enumeration value="parent"/>
      <xs:enumeration value="child"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="geometryType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="AbstractGeometry"/>
      <xs:enumeration value="Envelope"/>
      <xs:enumeration value="Point"/>
      <xs:enumeration value="AbstractSurface"/>
      <xs:enumeration value="Polygon"/>
      <xs:enumeration value="TriangulatedSurface"/>
      <xs:enumeration value="AbstractSolid"/>
      <xs:enumeration value="GeometricComplex"/>
      <xs:enumeration value="MultiPoint"/>
      <xs:enumeration value="MultiCurve"/>
      <xs:enumeration value="MultiSurface"/>
      <xs:enumeration value="MultiSolid"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== 3dcitydb/importer-exporter/impexp-core/src/main/resources/org/citydb/database/schema/3dcitydb-schema.xml
<?xml version="1.0" encoding="UTF-8"?>
<schemaMapping xmlns="http://www.3dcitydb.org/database/schema/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.3dcitydb.org/database/schema/1.0 3dcitydb-schema.xsd">

  <applicationSchemas>
    <schema id="core" xmlPrefix="core">
      <namespace context="citygml-2.0">http://www.opengis.net/citygml/2.0</namespace>
      <namespace context="citygml-1.0">http://www.opengis.net/citygml/1.0</namespace>
    </schema>
    <schema id="app" xmlPrefix="app">
      <namespace context="citygml-2.0">http://www.opengis.net/citygml/appearance/2.0</namespace>
      <namespace context="citygml-1.0">http://www.opengis.net/citygml/appearance/1.0</namespace>
    </schema>
    <schema id="bldg" xmlPrefix="bldg">
      <namespace context="citygml-2.0">http://www.opengis.net/citygml/building/2.0</namespace>
      <namespace context="citygml-1.0">http://www.opengis.net/citygml/building/1.0</namespace>
    </schema>
    <schema id="brid" xmlPrefix="brid">
      <namespace context="citygml-2.0">http://www.opengis.net/citygml/bridge/2.0</namespace>
    </schema>
    <schema id="frn" xmlPrefix="frn">
      <namespace context="citygml-2.0">http://www.opengis.net/citygml/cityfurniture/2.0</namespace>
      <namespace context="citygml-1.0">http://www.opengis.net/citygml/cityfurniture/1.0</namespace>
    </schema>
    <schema id="grp" xmlPrefix="grp">
      <namespace context="citygml-2.0">http://www.opengis.net/citygml/cityobjectgroup/2.0</namespace>
      <namespace context="citygml-1.0">http://www.opengis.net/citygml/cityobjectgroup/1.0</namespace>
    </schema>
    <schema id="gen" xmlPrefix="gen">
      <namespace context="citygml-2.0">http://www.opengis.net/citygml/generics/2.0</namespace>
      <namespace context="citygml-1.0">http://www.opengis.net/citygml/generics/1.0</namespace>
    </schema>
    <schema id="luse" xmlPrefix="luse">
      <namespace context="citygml-2.0">http://www.opengis.net/citygml/landuse/2.0</namespace>
      <namespace context="citygml-1.0">http://www.opengis.net/citygml/landuse/1.0</namespace>
    </schema>
    <schema id="dem" xmlPrefix="dem">
      <namespace context="citygml-2.0">http://www.opengis.net/citygml/relief/2.0</namespace>
      <namespace context="citygml-1.0">http://www.opengis.net/citygml/relief/1.0</namespace>
    </schema>
    <schema id="tran" xmlPrefix="tran">
      <namespace context="citygml-2.0">http://www.opengis.net/citygml/transportation/2.0</namespace>
      <namespace context="citygml-1.0">http://www.opengis.net/citygml/transportation/1.0</namespace>
    </schema>
    <schema id="tun" xmlPrefix="tun">
      <namespace context="citygml-2.0">http://www.opengis.net/citygml/tunnel/2.0</namespace>
    </schema>
    <schema id="veg" xmlPrefix="veg">
      <namespace context="citygml-2.0">http://www.opengis.net/citygml/vegetation/2.0</namespace>
      <namespace context="citygml-1.0">http://www.opengis.net/citygml/vegetation/1.0</namespace>
    </schema>
    <schema id="wtr" xmlPrefix="wtr">
      <namespace context="citygml-2.0">http://www.opengis.net/citygml/waterbody/2.0</namespace>
      <namespace context="citygml-1.0">http://www.opengis.net/citygml/waterbody/1.0</namespace>
    </schema>
    <schema id="gml" xmlPrefix="gml">
      <namespace context="citygml-2.0">http://www.opengis.net/gml</namespace>
      <namespace context="citygml-1.0">http://www.opengis.net/gml</namespace>
    </schema>
    <schema id="citydb" xmlPrefix="citydb">
      <namespace context="citygml-2.0">http://www.3dcitydb.org/citygml-ade/3.0</namespace>
      <namespace context="citygml-1.0">http://www.3dcitydb.org/citygml-ade/3.0</namespace>
    </schema>
  </applicationSchemas>

  <attributeTypes>
    <attributeType id="stringAttributeType" table="cityobject_genericattrib">
      <attribute path="@name" column="attrname" type="string" minOccurs="1" schema="gen"/>
      <attribute path="value" column="strval" type="string" minOccurs="1" schema="gen"/>
    </attributeType>

    <attributeType id="intAttributeType" table="cityobject_genericattrib">
      <attribute path="@name" column="attrname" type="string" minOccurs="1" schema="gen"/>
      <attribute path="value" column="intval" type="integer" minOccurs="1" schema="gen"/>
    </attributeType>

    <attributeType id="doubleAttributeType" table="cityobject_genericattrib">
      <attribute path="@name" column="attrname" type="string" minOccurs="1" schema="gen"/>
      <attribute path="value" column="realval" type="double" minOccurs="1" schema="gen"/>
    </attributeType>

    <attributeType id="uriAttributeType" table="cityobject_genericattrib">
      <attribute path="@name" column="attrname" type="string" minOccurs="1" schema="gen"/>
      <attribute path="value" column="urival" type="string" minOccurs="1" schema="gen"/>
    </attributeType>

    <attributeType id="dateAttributeType" table="cityobject_genericattrib">
      <attribute path="@name" column="attrname" type="string" minOccurs="1" schema="gen"/>
      <attribute path="value" column="dateval" type="date" minOccurs="1" schema="gen"/>
    </attributeType>

    <attributeType id="measureAttributeType" table="cityobject_genericattrib">
      <attribute path="@name" column="attrname" type="string" minOccurs="1" schema="gen"/>
      <complexAttribute path="value" schema="gen">
        <attribute path="." column="realval" type="double" minOccurs="1" schema="gen"/>
        <attribute path="@uom" column="unit" type="string" schema="gen"/>
      </complexAttribute>
    </attributeType>

    <attributeType id="genericAttributeSetType" table="cityobject_genericattrib">
      <attribute path="@name" column="attrname" type="string" minOccurs="1" schema="gen"/>
      <attribute path="@codeSpace" column="genattribset_codespace" type="string" schema="gen"/>
      <complexAttribute path="stringAttribute" type="stringAttributeType" schema="gen">
        <join table="cityobject_genericattrib" fromColumn="id" toColumn="parent_genattrib_id" toRole="child">
          <condition column="datatype" value="1" type="integer"/>
        </join>
      </complexAttribute>
      <complexAttribute path="intAttribute" type="intAttributeType" schema="gen">
        <join table="cityobject_genericattrib" fromColumn="id" toColumn="parent_genattrib_id" toRole="child">
          <condition column="datatype" value="2" type="integer"/>
        </join>
      </complexAttribute>
      <complexAttribute path="doubleAttribute" type="doubleAttributeType" schema="gen">
        <join table="cityobject_genericattrib" fromColumn="id" toColumn="parent_genattrib_id" toRole="child">
          <condition column="datatype" value="3" type="integer"/>
        </join>
      </complexAttribute>
      <complexAttribute path="uriAttribute" type="uriAttributeType" schema="gen">
        <join table="cityobject_genericattrib" fromColumn="id" toColumn="parent_genattrib_id" toRole="child">
          <condition column="datatype" value="4" type="integer"/>
        </join>
      </complexAttribute>
      <complexAttribute path="dateAttribute" type="dateAttributeType" schema="gen">
        <join table="cityobject_genericattrib" fromColumn="id" toColumn="parent_genattrib_id" toRole="child">
          <condition column="datatype" value="5" type="integer"/>
        </join>
      </complexAttribute>
      <complexAttribute path="measureAttribute" type="measureAttributeType" schema="gen">
        <join table="cityobject_genericattrib" fromColumn="id" toColumn="parent_genattrib_id" toRole="child">
          <condition column="datatype" value="6" type="integer"/>
        </join>
      </complexAttribute>
      <complexAttribute path="genericAttributeSet" type="genericAttributeSetType" schema="gen">
        <join table="cityobject_genericattrib" fromColumn="id" toColumn="parent_genattrib_id" toRole="child">
          <condition column="datatype" value="7" type="integer"/>
        </join>
      </complexAttribute>
    </attributeType>
  </attributeTypes>
  
  <objectTypes>
    <!-- GML module -->
    <objectType id="AbstractGMLType" path="_GML" table="cityobject" objectClassId="1" schema="gml" abstract="true">
      <attribute path="@id" column="gmlid" type="string" schema="gml"/>
      <attribute path="description" column="description" type="string" schema="gml"/>
      <complexAttribute path="name" schema="gml">
        <attribute path="." column="name" type="string" schema="gml"/>
        <attribute path="@codeSpace" column="name_codespace" type="string" schema="gml"/>
      </complexAttribute>
      <attribute path="id" column="id" type="integer" queryable="false" schema="citydb"/>
      <attribute path="objectclass_id" column="objectclass_id" type="integer" queryable="false" schema="citydb"/>
    </objectType>
  </objectTypes>

  <featureTypes>
    <!-- GML module -->
    <featureType id="AbstractFeatureType" path="_Feature" table="cityobject" schema="gml" objectClassId="2" abstract="true">
      <attribute path="@id" column="gmlid" type="string" schema="gml"/>
      <attribute path="description" column="description" type="string" schema="gml"/>
      <complexAttribute path="name" schema="gml">
        <attribute path="." column="name" type="string" schema="gml"/>
        <attribute path="@codeSpace" column="name_codespace" type="string" schema="gml"/>
      </complexAttribute>
      <geometryProperty path="boundedBy" inlineColumn="envelope" type="Envelope" schema="gml"/>
      <attribute path="id" column="id" type="integer" queryable="false" schema="citydb"/>
      <attribute path="objectclass_id" column="objectclass_id" type="integer" queryable="false" schema="citydb"/>
      <attribute path="lastModificationDate" column="last_modification_date" type="timestamp" schema="citydb"/>
      <attribute path="updatingPerson" column="updating_person" type="string" schema="citydb"/>
      <attribute path="reasonForUpdate" column="reason_for_update" type="string" schema="citydb"/>
